### ISSUE TITLE
Bug Report: Inability to View Contracts for Selected DTE after Manually Setting Date

### ISSUE THREAD

**Issue by hash123shaikh** [charmtraders-apps/issue_tracker#9]
**Summary:**
Encountered an issue within the OptiTrade tool where, despite manually setting a date in the YYYYMMDD format and selecting a specific Date-to-Expiration (DTE), the tool fails to display the corresponding contracts.

**Steps to Reproduce:**
1.	Launch the OptiTrade tool and navigate to the section where you can select a database for contract analysis.
2.	Manually input a date in the required YYYYMMDD format.
3.	Select a desired DTE to view contracts that should be available for that specific expiration period.
4.	Observe the tool's response and the availability of contract data for the selected DTE.

**Expected Behaviour:**
Upon selecting a specific DTE after manually setting a date, the tool should display all available contracts corresponding to the chosen expiration period, allowing for further analysis or trading actions.

**Actual Behaviour:**
After setting a date manually and choosing a DTE, the tool does not display any contracts for the selected expiration period, leaving the user without the expected data for analysis or trading decisions.

**Frequency:**
This issue occurs rarely when attempting to view contracts for a selected DTE after manually setting a date.
![ss_6](https://github.com/charmtraders-apps/issue_tracker/assets/80396371/907db4ed-eac8-4140-ac27-c0ddbf50912f)

**Comment by charmtraders-apps** [comment]
Thank you for bringing this issue to our attention. We have carefully reviewed the steps you provided to replicate the error within the OptiTrade tool concerning the inability to display contracts after manually setting a date and selecting a specific Date-to-Expiration (DTE).

Initial Investigation:
Upon initial testing, we were unable to replicate the issue as described. The tool functioned as expected in most scenarios, correctly displaying available contracts corresponding to the selected DTE after a date was manually input.

Next Steps:
However, we acknowledge the importance of your experience and the discrepancy it presents. We are committed to ensuring the reliability and accuracy of the OptiTrade tool. To this end, we will conduct a more thorough investigation into the matter. Our team will delve deeper into the tool's functionalities and examine all related systems to uncover any underlying issues that may intermittently affect the display of contract data as you described.

Further Assistance:
We appreciate your patience as we work to resolve this matter. If you encounter any other issues or have additional information that could assist our investigation, please do not hesitate to reach out. Your input is invaluable in helping us improve the tool's performance and user experience.

Conclusion:
Rest assured, we are dedicated to identifying and addressing the root cause of the problem you've encountered. We aim to ensure that the OptiTrade tool meets our users' needs efficiently and effectively, providing reliable data for analysis and trading decisions.

Thank you for your understanding and cooperation.


![Screenshot 2024-02-28 at 12 49 40](https://github.com/charmtraders-apps/issue_tracker/assets/151726541/30139891-f2f9-4efd-961d-f93ccd22e46d)

**Comment by hash123shaikh** [comment]
Thank you for your attention to the issue I previously reported regarding the difficulty in displaying contracts after manually setting a date and selecting a Date-to-Expiration (DTE) within the OptiTrade tool. I appreciate the team's efforts to investigate and resolve this matter.

I wanted to provide an update that might be relevant to your investigation. After experiencing the issue on my primary system, I attempted to replicate the process on a different system to rule out any device-specific problems. Unfortunately, I encountered the same issue on the second system, where I was still unable to view the contracts for the selected DTE after manually inputting the date. This was surprising as the issue seems to persist across different environments, which was not the case previously.

This new information might suggest that the problem could be related to the tool itself rather than specific user environments. I'm unsure of the exact cause, especially since this functionality worked as expected in the past. Recent updates or changes within the tool might be contributing to this anomaly.

I hope this additional information can assist in narrowing down the potential causes of the issue. I'm committed to working with your team to resolve this and am available to provide any further details or assistance required. Please let me know if there are specific tests or information you need that could help in your investigation.

Thank you once again for your dedication to ensuring the OptiTrade tool functions optimally for all its users. I look forward to your guidance on how to navigate this issue.

**Comment by charmtraders-apps** [comment]
Thank you for your thorough update and for taking the time to test the issue across different systems. You're correct; the problem seems to be with the OptiTrade tool itself rather than the user environment. We have just released a new update aimed at resolving this issue. However, pinpointing the exact root cause remains challenging since we haven't been able to replicate the problem on our end. Please install the latest update and let us know if it resolves the issue for you. Your feedback is invaluable in ensuring the tool functions optimally for all users.

**Comment by hash123shaikh** [comment]
I'm pleased to report that after installing the latest update to the OptiTrade tool, the previously encountered issue with displaying contracts for selected Dates-to-Expiration (DTE) has been successfully resolved. I have tested the functionality across the same conditions that initially presented the problem, and I can now see the contracts as expected.

This resolution significantly enhances the usability and reliability of the tool, and I wanted to express my gratitude for your team's swift action to address the feedback. The update has not only rectified the issue but also reinforced my confidence in the OptiTrade tool and the support team behind it.

Thank you once again for your commitment to continuous improvement and for maintaining open communication with your users. I look forward to continuing to use the OptiTrade tool and contributing to its ongoing refinement.
